// 24 endpoint Sectors dibungkus sebagai tool dengan schema + validator sendiri (bukti "custom tool-use pipeline" §5 PRD).
// Kolom `pillars` menentukan agen mana yang boleh memanggilnya — routing antar sumber terjadi di sini, bukan di prompt.
export type ToolName = keyof typeof TOOL_SPECS;
type P = Record<string, { type: "string"; desc: string; required?: boolean }>;

export interface ToolSpec {
  path: string;
  params: P;
  desc: string;
  cache: "universe" | "holders" | "daily" | "news" | "helper";
  credits: number;
  paginated?: boolean;
  pillars: ("mover" | "katalis" | "flow" | "grup" | "fundamental")[];
  timeout?: number;
}

export const TOOL_SPECS = {
  close: { path: "/close/", params: { date: { type: "string", desc: "YYYY-MM-DD, default hari trading terakhir" } }, desc: "Harga close SEMUA ticker IDX pada satu hari (paginated).", cache: "universe", credits: 32, paginated: true, pillars: ["mover"] },
  daily: { path: "/daily/{symbol}/", params: { symbol: { type: "string", desc: "ticker IDX, mis. BBCA", required: true }, start: { type: "string", desc: "YYYY-MM-DD (maks rentang 90d)" }, end: { type: "string", desc: "YYYY-MM-DD" } }, desc: "OHLC + volume + market_cap harian satu ticker.", cache: "daily", credits: 1, pillars: ["mover", "fundamental"] },
  top_changes: { path: "/companies/top-changes/", params: { classifications: { type: "string", desc: "top_gainers,top_losers" }, periods: { type: "string", desc: "1d,7d,14d,30d,365d" }, n_stock: { type: "string", desc: "jumlah per kategori" } }, desc: "Gainers & losers lintas periode.", cache: "universe", credits: 10, pillars: ["mover"] },
  most_traded: { path: "/most-traded/", params: { start: { type: "string", desc: "YYYY-MM-DD" }, end: { type: "string", desc: "YYYY-MM-DD" }, n_stock: { type: "string", desc: "mis. 20" } }, desc: "Saham teraktif per hari.", cache: "universe", credits: 2, pillars: ["mover"] },
  index_daily: { path: "/index-daily/{index_code}/", params: { index_code: { type: "string", desc: "mis. IDXCOMPOSITE", required: true }, start: { type: "string", desc: "YYYY-MM-DD" }, end: { type: "string", desc: "YYYY-MM-DD" } }, desc: "Close indeks pasar harian.", cache: "universe", credits: 1, pillars: ["mover"] },
  idx_total: { path: "/idx-total/", params: { start: { type: "string", desc: "YYYY-MM-DD" }, end: { type: "string", desc: "YYYY-MM-DD" } }, desc: "Kapitalisasi pasar total IDX.", cache: "universe", credits: 1, pillars: ["mover"] },
  broker_summary: { path: "/broker-summary/{symbol}/", params: { symbol: { type: "string", desc: "ticker", required: true }, start: { type: "string", desc: "YYYY-MM-DD (rentang maks 14 hari)" }, end: { type: "string", desc: "YYYY-MM-DD" } }, desc: "Aktivitas per broker per hari untuk satu saham: bval/sval/nval (IDR).", cache: "daily", credits: 1, pillars: ["flow"] },
  broker_summary_top: { path: "/broker-summary/{symbol}/top/", params: { symbol: { type: "string", desc: "ticker", required: true }, start: { type: "string", desc: "YYYY-MM-DD" }, end: { type: "string", desc: "YYYY-MM-DD" }, n_brokers: { type: "string", desc: "mis. 10" } }, desc: "Top akumulasi/distribusi broker untuk satu saham.", cache: "daily", credits: 2, pillars: ["flow"] },
  brokers_top: { path: "/brokers/top/", params: { date: { type: "string", desc: "YYYY-MM-DD" }, metric: { type: "string", desc: "gross_value|net_flow" }, n_brokers: { type: "string", desc: "mis. 20" }, cohort: { type: "string", desc: "retail|mixed|institutional|unknown" }, origin: { type: "string", desc: "foreign|domestic" } }, desc: "Peringkat broker harian (konteks market per kohort).", cache: "daily", credits: 2, pillars: ["flow"] },
  broker_registry: { path: "/brokers/", params: { cohort: { type: "string", desc: "retail|mixed|institutional|unknown" }, origin: { type: "string", desc: "foreign|domestic" } }, desc: "Registry broker IDX: code, name, is_foreign, cohort, license_type.", cache: "helper", credits: 1, pillars: ["flow"] },
  broker_activity: { path: "/broker-activity/{broker_code}/", params: { broker_code: { type: "string", desc: "kode broker, mis. MG", required: true }, symbol: { type: "string", desc: "filter ticker" }, start: { type: "string", desc: "YYYY-MM-DD (maks 14d)" }, end: { type: "string", desc: "YYYY-MM-DD" } }, desc: "Semua (saham,hari) yang diperdagangkan satu broker.", cache: "daily", credits: 1, pillars: ["flow"] },
  foreign_flow: { path: "/foreign-flow/{symbol}/", params: { symbol: { type: "string", desc: "ticker", required: true }, start: { type: "string", desc: "YYYY-MM-DD (maks 90d)" }, end: { type: "string", desc: "YYYY-MM-DD" } }, desc: "Net inflow asing harian (domestik = -nya).", cache: "daily", credits: 1, pillars: ["flow"] },
  filings: { path: "/filings/", params: { symbol: { type: "string", desc: "ticker" }, transaction_type: { type: "string", desc: "buy|sell" }, holder_type: { type: "string", desc: "direksi|komut|..." }, start: { type: "string", desc: "YYYY-MM-DD" }, end: { type: "string", desc: "YYYY-MM-DD" } }, desc: "Filing transaksi insider/pemegang besar.", cache: "news", credits: 1, paginated: true, pillars: ["flow", "katalis"] },
  news: { path: "/news/", params: { extension: { type: "string", desc: "idx|mining" }, symbols: { type: "string", desc: "comma, mis. BBCA,BBRI" }, keyword: { type: "string", desc: "substring judul" }, tags: { type: "string", desc: "slug tag" }, sector: { type: "string", desc: "slug sektor" }, sub_sector: { type: "string", desc: "slug subsektor" }, start: { type: "string", desc: "YYYY-MM-DD" }, end: { type: "string", desc: "YYYY-MM-DD" } }, desc: "Berita IDX/mining dengan timestamp, source, tags, symbols.", cache: "news", credits: 1, paginated: true, pillars: ["katalis"] },
  tags: { path: "/tags/", params: {}, desc: "Semua slug tag berita/filing.", cache: "helper", credits: 1, pillars: ["katalis"] },
  subsectors: { path: "/subsectors/", params: {}, desc: "Semua slug sektor/subsektor kebab-case — WAJIB sumber nilai sub_sector sebelum memanggil subsector_report.", cache: "helper", credits: 1, pillars: ["fundamental", "katalis"] },
  corporate_actions: { path: "/company/corporate-actions/{symbol}/", params: { symbol: { type: "string", desc: "ticker", required: true } }, desc: "Dividen, split, rights issue, AGM.", cache: "holders", credits: 1, pillars: ["katalis"] },
  suspensions: { path: "/suspensions/", params: { symbol: { type: "string", desc: "ticker" }, start: { type: "string", desc: "YYYY-MM-DD" }, end: { type: "string", desc: "YYYY-MM-DD" } }, desc: "Riwayat suspend IDX: symbol, suspension_date, reason.", cache: "universe", credits: 1, paginated: true, pillars: ["katalis"] },
  free_float: { path: "/free-float/", params: { sector: { type: "string", desc: "slug sektor (filter tunggal)" }, sub_sector: { type: "string", desc: "slug subsektor" } }, desc: "Free float % per emiten (Public share).", cache: "universe", credits: 3, paginated: true, pillars: ["katalis", "fundamental"] },
  company_report: { path: "/company/report/{symbol}/", params: { symbol: { type: "string", desc: "ticker", required: true }, sections: { type: "string", desc: "overview,valuation,future,peers,financials,dividend,management,ownership" } }, desc: "Laporan perusahaan per section (ownership = major_shareholders + conglomerates_group).", cache: "holders", credits: 1, pillars: ["grup", "fundamental"] },
  quarterly_financials: { path: "/financials/quarterly/{symbol}/", params: { symbol: { type: "string", desc: "ticker", required: true }, n_quarters: { type: "string", desc: "mis. 8" } }, desc: "Laba rugi + neraca kuartalan.", cache: "holders", credits: 8, pillars: ["fundamental"] },
  company_segments: { path: "/company/get-segments/{symbol}/", params: { symbol: { type: "string", desc: "ticker", required: true }, financial_year: { type: "string", desc: "mis. 2025" } }, desc: "Segmen pendapatan/biaya per tahun.", cache: "holders", credits: 1, pillars: ["fundamental"] },
  shareholders_composition: { path: "/company/shareholders-composition/{symbol}/", params: { symbol: { type: "string", desc: "ticker", required: true }, year: { type: "string", desc: "mis. 2026" } }, desc: "Komposisi pemegang per kategori (individual_l, corporate_l, *_f ...) bulanan.", cache: "holders", credits: 1, pillars: ["grup"] },
  subsector_report: { path: "/subsector/report/{sub_sector}/", params: { sub_sector: { type: "string", desc: "slug kebab, mis. coal", required: true }, sections: { type: "string", desc: "statistics,market_cap,stability,valuation,growth,companies" } }, desc: "Median PE/PB subsektor utk pembanding valuasi.", cache: "universe", credits: 6, pillars: ["fundamental"] },
  screener: { path: "/companies/", params: { q: { type: "string", desc: "natural language (internal saja)" }, where: { type: "string", desc: "mis. sub_sector='coal'" }, order_by: { type: "string", desc: "mis. -market_cap" }, limit: { type: "string", desc: "mis. 50" } }, desc: "Screener universe emiten (internal, tidak dipamerkan).", cache: "universe", credits: 1, paginated: true, pillars: ["fundamental", "grup"] },
  listing_performance: { path: "/listing-performance/{symbol}/", params: { symbol: { type: "string", desc: "ticker", required: true } }, desc: "Performa 7/30/90/365 hari sejak listing.", cache: "daily", credits: 1, pillars: ["mover"] },
} satisfies Record<string, ToolSpec>;
